### ISSUE TITLE
@svelte-put/lockscroll: show error when use:lockscroll opn svelte:document

### ISSUE THREAD

**Issue by lynhan318** [vnphanquang/svelte-put#233] opened 2023-10-09 09:34 UTC
Hi, Thanks for the awesome svelte project. 

I follow the instructions [here](https://github.com/vnphanquang/svelte-put/tree/main/packages/actions/lockscroll)  to implement lockscroll actions but face with the issue below:

This is my implement:
```svelte
<script lang="ts">
  import {lockscroll, createLockScrollStore} from '@svelte-put/lockscroll';
  const locked = createLockScrollStore();
  $: {
    locked.set(!!visibleNode);
  }
</script>

<svelte:document use:lockscroll={locked} />

```
![image](https://github.com/vnphanquang/svelte-put/assets/32099104/240112e2-6ec0-49d5-aad7-330feecf6002)

The error throw from:
![image](https://github.com/vnphanquang/svelte-put/assets/32099104/42a567d2-a7b2-4573-96d4-43400cc63dd5)

It works fine on `<svelte:body/>`

**Comment by vnphanquang** [comment] 2023-10-09 09:58
Hey there @lynhan318 thank you very much for the report. The issue is fixed in the latest release [@svelte-put/lockscroll@1.0.1](https://github.com/vnphanquang/svelte-put/releases/tag/%40svelte-put%2Flockscroll%401.0.1) just now (through [this commit](https://github.com/vnphanquang/svelte-put/commit/640e2d54bca3672c63b318d7364d9c5dc518f867)). Please feel free to reopen if you are still having the same issue.

Cheers!

**Closed by vnphanquang** 2023-10-09 09:58 UTC
Labels: type:bug, priority:high, scrop:lockscroll
